services:
  app:
    image: python:3.10
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8013:5000"  # map cổng hệ thống -> cổng container
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python -m app.app"
    networks:
      - app_network
    env_file:
      - .env

networks:
  app_network:
    driver: bridge
